server:
  port: 80

  ssl:
    key-store: classpath:test.jks
    key-store-password: ksp12345
    key-password: kp12345

management:
  security:
    enabled: false #actuator高级信息权限开关

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: 12345
      database: test
      authenticationDatabase: admin
